// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnzuackyikkacyufrbcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuenVhY2t5aWtrYWN5dWZyYmNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTgzMjksImV4cCI6MjA2MjI5NDMyOX0.2UXjBh9YiNkZ__blKXUiRLk6rnhg_k3YU-oPIidDQDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);